#!/bin/bash
echo '#!/bin/bash' > 22-users_and_homes
echo "cut -d":" --fields=1,6 /etc/passwd | sort"  >> 22-users_and_homes
chmod u+x 22-users_and_homes
git add .
git commit -m '22-users_and_homes'
git push
