#!/usr/bin/env bash
# HaProxy installation and configuration
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install haproxy=2.6.\*
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 4584-web-01 54.88.246.15 check\n\tserver server 4584-web-02 54.86.33.48 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy start
