#!/usr/bin/env bash
# a Bash script that displays Best School 10 times using while loop

i=0
while [ $i -lt 10 ];
do
	if [[ $i == 8 ]]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++));
done
