#!/usr/bin/env bash
# a Bash script that displays Best School 10 times using while loop

i=1
while [ $i -le 10 ];
do
	if [[ $i == 4 ]]
	then
		echo "bad luck"
	elif [[ $i == 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++));
done
